title: Hugo Caselles-Dupré ![photo](https://github.com/Caselles/caselles.github.io/blob/master/photo_these.png)
description: PhD candidate in Machine Learning (ENSTA ParisTech - Softbank Robotics Europe)
theme: jekyll-theme-cayman
